### PR TITLE
Issue 1

### PR DESCRIPTION
**Pull request by rouazana**
Add missing attributes for #1

### CODE REVIEW

**Comment by coudot** [comment]
Hi, some remarks:
* The version should be 1.4 (latest release is 1.3)
* Build failed, you may have to fix the repo to get the lsc-core.jar

**Comment by rouazana** [comment]
> The version should be 1.4 (latest release is 1.3)

Good catch, sorry.

> Build failed, you may have to fix the repo to get the lsc-core.jar

Fixed (but for oracle7, but it seems to be a travis issue)

**Review by coudot — CHANGES_REQUESTED** [review]
It would be better to change file name in lsc-obm-plugin.docs

**Comment by rouazana** [comment]
> It would be better to change file name in lsc-obm-plugin.docs

Done

**Review by coudot — APPROVED** [review]

**Pull request merged**
